name: Android Dev Build CI
on:
  pull_request:
    branches: ["staging"]
  push:
    branches: ["staging"]

jobs:
  build-and-release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: 3.27.1
          channel: stable

      - name: Install project dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release -v

      - name: Verify APK Build
        run: ls -la build/app/outputs/flutter-apk/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          path: "build/app/outputs/flutter-apk/app-release.apk"
          name: EposMachine-android-${{github.ref_name}}.apk
          retention-days: 5
          if-no-files-found: error
          compression-level: 0 