name: Android Release CI
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  build-and-release-android:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: eeezeeerp
            url: "https://eeezeeerp.cloudposai.com"
          - name: eposdemo
            url: "https://eposdemo.yougoit.in"
          - name: linetolinepos
            url: "https://linetolinepos.yougoit.in"
          - name: hypersouq
            url: "https://epos.hypersouq.in"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: 3.35.1
          channel: stable

      - name: Install project dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release -v --dart-define=BASE_URL=${{ matrix.url }}

      - name: Verify APK Build
        run: ls -la build/app/outputs/flutter-apk/

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/cloudpos.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          path: "build/app/outputs/flutter-apk/cloudpos.apk"
          name: cloudpos-${{ matrix.name }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/cloudpos.apk
          draft: true
          prerelease: true
          generate_release_notes: true

      - name: Set Drive Folder ID
        run: |
          if [ "${{ matrix.name }}" == "eeezeeerp" ]; then echo "DRIVE_FOLDER_ID=${{ secrets.GDRIVE_FOLDER_ID_EEEZEEERP }}" >> $GITHUB_ENV; fi
          if [ "${{ matrix.name }}" == "eposdemo" ]; then echo "DRIVE_FOLDER_ID=${{ secrets.GDRIVE_FOLDER_ID_EPOSDEMO }}" >> $GITHUB_ENV; fi
          if [ "${{ matrix.name }}" == "linetolinepos" ]; then echo "DRIVE_FOLDER_ID=${{ secrets.GDRIVE_FOLDER_ID_LINETOLINEPOS }}" >> $GITHUB_ENV; fi
          if [ "${{ matrix.name }}" == "hypersouq" ]; then echo "DRIVE_FOLDER_ID=${{ secrets.GDRIVE_FOLDER_ID_HYPERSOUQ }}" >> $GITHUB_ENV; fi

      - name: Upload to Google Drive
        if: ${{ env.DRIVE_FOLDER_ID != '' }}
        uses: adityak74/google-drive-upload-git-action@v4.9
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: build/app/outputs/flutter-apk/cloudpos.apk
          folderId: ${{ env.DRIVE_FOLDER_ID }}
          name: cloudpos.apk
          overwrite: "true"