name: Android Release CI
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          generate_release_notes: true

  build-and-release-android:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: eeezeeerp
            url: "https://eeezeeerp.cloudposai.com"
          - name: eposdemo
            url: "https://eposdemo.yougoit.in"
          - name: linetolinepos
            url: "https://linetolinepos.yougoit.in"
          - name: hypersouq
            url: "https://epos.hypersouq.in"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: 3.35.1
          channel: stable

      - name: Install project dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release -v --dart-define=BASE_URL=${{ matrix.url }}

      - name: Verify APK Build
        run: ls -la build/app/outputs/flutter-apk/

      - name: Rename APK for GitHub Release
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/cloudpos-${{ matrix.name }}.apk

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/cloudpos-${{ matrix.name }}.apk
          draft: true
          prerelease: true