name: Build and Package Flutter Windows App

on:
  push:
    branches:
      - gokul-dev
  pull_request:
    branches:
      - gokul-dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1" # Adjust to match your Flutter version
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Windows Support
        run: flutter config --enable-windows-desktop

      - name: Build Flutter Windows App
        run: flutter build windows --release

      - name: Install Inno Setup
        run: |
          choco install innosetup -y
          echo "C:\Program Files (x86)\Inno Setup 6" >> $env:GITHUB_PATH

      - name: Compile Inno Setup Installer
        run: iscc "${{ github.workspace }}/installers/github_action_windows_inno_script.iss"

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: latest
          release_name: "Latest Release"
          draft: false
          prerelease: false
          files: ${{ github.workspace }}/installers/EposMachine.exe
