name: Release CI
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  build-and-release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: buildbranch

      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: 3.35.1
          channel: stable

      - name: Install project dependencies
        run: flutter pub get

      - name: Build artifacts
        run: flutter build windows --release -v

      - name: Copy DLLs to Release Folder
        run: |
          cp dependencies/*.dll build/windows/x64/runner/Release/

      - name: Verify Files in Release Directory
        run: dir build/windows/x64/runner/Release/

      - name: Install Inno Setup
        run: |
          choco install innosetup --yes --no-progress

      - name: Build Installer
        run: iex ("& {0} {1} {2}" -f '"C:\Program Files (x86)\Inno Setup 6\iscc.exe"',"/DMyAppVersion='${{github.ref_name}}'", ".\inno_setup.iss")

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          path: "Output/*.exe"
          name: EposMachine-windows-${{github.ref_name}}.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Output/*.exe
          draft: true
          prerelease: true
          generate_release_notes: true
